### ISSUE TITLE
Severity Mapping

### ISSUE THREAD

**Issue by SCRE1020** [olsh/dotnet-reqube#1]
Hi,

I have two questions/suggestions regarding the mapping of severity as defined in "Constants.cs":
`{ "ERROR", "BLOCKER" },
                    { "WARNING", "CRITICAL" },
                    { "SUGGESTION", "MAJOR" },
                    { "HINT", "MINOR" },
{ "INFO", "INFO" }`

1) According to ReSharpers documentation, it does not use "INFO". So why is there a mapping from INFO to INFO? (https://www.jetbrains.com/help/resharper/Code_Analysis__Code_Inspections.html#severity)

2) The mapping from WARNING to CRITICAL seems like an escalation to me. R# WARNINGs "represent serious coding inefficiencies" while a SonarQube CRITICAL item might "cause the application to crash or to corrupt stored data". In my humble opinion, MAJOR would be a better fit for WARNING, althought still not 100% exact because of the different semantics behind the two calssifications. (https://docs.sonarqube.org/7.4/user-guide/rules/)

Greetings

PS: Thanks for sharing this useful tool with the public, I really appreciate it.

**Comment by olsh** [comment]
Hi @SCRE1020,

I'm glad that you find the tool useful.

> According to ReSharpers documentation, it does not use "INFO". So why is there a mapping from INFO to INFO? (https://www.jetbrains.com/help/resharper/Code_Analysis__Code_Inspections.html#severity)

Well, according to [this page](https://www.jetbrains.com/help/resharper/InspectCode.html#configuring-inspectcode-with-command-line-parameters), there is `INFO` level. But I've never seen it in reports.

> The mapping from WARNING to CRITICAL seems like an escalation to me. R# WARNINGs "represent serious coding inefficiencies" while a SonarQube CRITICAL item might "cause the application to crash or to corrupt stored data". In my humble opinion, MAJOR would be a better fit for WARNING, althought still not 100% exact because of the different semantics behind the two calssifications. (https://docs.sonarqube.org/7.4/user-guide/rules/)

I think you're right. I wanted to change this while ago, but had some doubts.
Will update this soon.
