### ISSUE TITLE
Failed to read external issues report while uploading to SonarQube

### ISSUE THREAD

**Issue by NextNebula** [olsh/dotnet-reqube#2]
Resharper codeinspect does not generate an XML for all my projects in the solution as some of the projects have no issues. Because of that the upload to SonarQube fails because it expects an generated json in all the project folders. So I get the error failed to read external issues report.

Anyone else who experienced this and knows how to deal with this?

**Comment by olsh** [comment]
Hi @EarthlingRich 

Thanks for the reporting, fixed.
