### ISSUE TITLE
Issue with latest 1.20 version 

### ISSUE THREAD

**Issue by SebastienHo** [olsh/dotnet-reqube#8]
Hi,

With latest version, I got the following error with my code :

"SonarQube C# Analysis Fails to 'Not a Valid Line Offset for Pointer'"

It looks like the convertion to sonar does not compute correct end of line.

Here is resharper line :

```<Issue TypeId="RedundantUsingDirective" File="src\CampaignManagement.api\Controllers\v1\BlacklistController.cs" Offset="174-215" Line="7" Message="Using directive is not required by the code and can be safely removed" />```

It is converted to :

```{
         "engineId":"R#",
         "primaryLocation":{
            "filePath":"D:\\Projects\\git\\CampainManagement.api\\src\\CampaignManagement.api\\Controllers\\v1\\BlacklistController.cs",
            "message":"Using directive is not required by the code and can be safely removed",
            "textRange":{
               "endColumn":42,
               "endLine":7,
               "startColumn":1,
               "startLine":7
            }
         },
         "ruleId":"RedundantUsingDirective",
         "severity":"MAJOR",
         "type":"CODE_SMELL"
      }```

End of column should be 41 not 42.

**Comment by olsh** [comment]
I just released version 1.2.4, where the issue was fixed.
Feel free to reopen the issue if you are still experiencing the problem.

**Comment by SebastienHo** [comment]
Still having issues with latest version : 

ERROR: Error during SonarQube Scanner execution
ERROR: 221 is not a valid line offset for pointer. File src/TraceParts.Apollo.web/Caches/Repositories/v6/CatalogRepository.cs has 19 character(s) at line 33
ERROR:
The SonarQube Scanner did not complete successfully
11:45:30.945  Post-processing failed. Exit code: 1

**Comment by olsh** [comment]
Hi @SebastienHo 

Could you please attach the SonarQube output file (or the part with the issue) and R# analysis file?

**Comment by SebastienHo** [comment]
Attached the files
[test.zip](https://github.com/olsh/dotnet-reqube/files/4509309/test.zip)

**Comment by olsh** [comment]
Are you sure you send me the correct files?
In the R# analysis, I can see the following issue in `CatalogRepository.cs`
```xml
      <Issue TypeId="RedundantUsingDirective" File="src\TraceParts.Apollo.data.elasticsearch\Repositories\v6\CatalogRepository.cs" Offset="103-127" Line="6" Message="Using directive is not required by the code and can be safely removed" />
      <Issue TypeId="CSharpWarnings::CS0618" File="src\TraceParts.Apollo.data.elasticsearch\Repositories\v6\CatalogRepository.cs" Offset="2900-2936" Line="73" Message="Obsolete (Schema v6)" />
```

in SonarQube JSON file the issues were converted to
```json
        {
            "engineId": "R#",
            "primaryLocation": {
                "filePath": "C:\\agents\\dev-traceparts-com\\_work\\16\\s\\project\\src\\TraceParts.Apollo.data.elasticsearch\\Repositories\\v6\\CatalogRepository.cs",
                "message": "Using directive is not required by the code and can be safely removed",
                "textRange": {
                    "endColumn": 24,
                    "endLine": 6,
                    "startColumn": 0,
                    "startLine": 6
                }
            },
            "ruleId": "RedundantUsingDirective",
            "severity": "MAJOR",
            "type": "CODE_SMELL"
        },
        {
            "engineId": "R#",
            "primaryLocation": {
                "filePath": "C:\\agents\\dev-traceparts-com\\_work\\16\\s\\project\\src\\TraceParts.Apollo.data.elasticsearch\\Repositories\\v6\\CatalogRepository.cs",
                "message": "Obsolete (Schema v6)",
                "textRange": {
                    "endColumn": 130,
                    "endLine": 73,
                    "startColumn": 94,
                    "startLine": 73
                }
            },
            "ruleId": "CSharpWarnings::CS0618",
            "severity": "MAJOR",
            "type": "CODE_SMELL"
        },
```

There is no line 33 and offset 221

**Comment by SebastienHo** [comment]
Attached are all the files I got after reqube :
[test.zip](https://github.com/olsh/dotnet-reqube/files/4509519/test.zip)

Test 'CatalogRepository.cs' is found in sonar_qube_report_5 and sonar_qube_report_9 files.

**Comment by SebastienHo** [comment]
It looks like it is 

```
Line 366:       <Issue TypeId="CSharpErrors"  File="src\TraceParts.Apollo.web\Caches\Repositories\v6\CatalogRepository.cs" Offset="1177-1386" Line="33" Message="Constructor 'Object' has 0 parameter(s) but is invoked with 7 argument(s)" />
```
in the original file.

**Comment by olsh** [comment]
Could you please check line endings of the `CatalogRepository.cs` file?
If it's windows (CRLF), then please change it to Unix(LF) just for tests.

**Comment by SebastienHo** [comment]
No changes, it still the same. I don't think it is linked with CRCF. Otherwise, we would have the problem on other file.

I reverted to 1.0.8 and it don't have the issue.

**Comment by olsh** [comment]
@SebastienHo thanks for the feedback, could you please update to 1.2.6 version?
I've added offset validations in the version.

**Comment by SebastienHo** [comment]
Sorry. I haven't tested it yet. I'll try to do it sometimes this week.
